(setq c-default-style "K&R")
(setq column-number-mode t)
(setq-default indent-tabs-mode t)
(setq-default c-basic-offset 8)
(setq-default inhibit-startup-message t)
(load-file "~/.emacs.d/themes/color-themes/billw-theme.el")
